### ISSUE TITLE
Physical dimensions precision

### ISSUE THREAD

**Issue by tischi** [tischi/fiji-plugin-yaml-metadata#1]
Should we limit the precision of the physical dimensions by rounding?
This might also solve the issue that their are distributed across multiple lines.

**Comment by oodegard** [comment]
I would in principle be against that, since some images from e.g. super res data have a very different resolution, compared to confocal data. I guess we risk losing compatibility in these cases if we do this?

**Comment by tischi** [comment]
Good point. I will leave it for now...
