### ISSUE TITLE
Discussion: Is ?? the best NA/NULL holder?

### ISSUE THREAD

**Issue by oodegard** [tischi/fiji-plugin-yaml-metadata#5]
For empty fields we now use ??.
Is this already defined in yaml as the null value or would it be better to have NA?
in R yaml a compleatly empty filed,  NA, or NULL is automatically recognized as empty and can be removed easily if missing. If we have ?? we need to handle this for each case.

**Comment by tischi** [comment]
changed ??? to NA
https://github.com/tischi/fiji-plugin-yaml-metadata/commit/8109b623b275ef9c44beb6fc9ff9128054284b4c
