### ISSUE TITLE
Run on all images in a folder

### ISSUE THREAD

**Issue by oodegard** [tischi/fiji-plugin-yaml-metadata#8]
can we make this run on all images in a folder if you select a path, and only one image if you select an image.

**Comment by tischi** [comment]
Type YAML into Fiji search bar.
Try using the [Batch] button.
Does that suffice or shall I modify something?
<img width="821" alt="image" src="https://user-images.githubusercontent.com/2157566/47767229-0e13d580-dd16-11e8-960a-6dfbcf9a7c42.png">
